// js/settings.js
import { openDrawer, navigate, state } from './app.js';
import { db } from './db.js';
import { api } from './api.js';

export function render(container) {
  const settings = db.getSettings();

  container.innerHTML = `
    <div class="screen">
      <div class="screen-header">
        <button class="hamburger" id="set-menu" aria-label="Menu">
          <span></span><span></span><span></span>
        </button>
        <span class="screen-title">Settings</span>
        <div style="width:28px"></div>
      </div>
      <div class="screen-body safe-bottom">
        <label class="field-label" for="set-worker-url">Cloudflare Worker URL</label>
        <input id="set-worker-url" class="input" type="url" placeholder="https://dreamlog-worker.your-name.workers.dev">
        <p style="font-size:11px;color:var(--text-ghost);margin-top:4px">Your deployed Cloudflare Worker endpoint</p>

        <div class="mt-16">
          <label class="field-label" for="set-vapid">VAPID Public Key (Phase 3)</label>
          <input id="set-vapid" class="input" type="text" placeholder="Generated by scripts/generate-vapid.js">
          <p style="font-size:11px;color:var(--text-ghost);margin-top:4px">Run <code style="background:var(--bg-elevated);padding:1px 5px;border-radius:3px">node scripts/generate-vapid.js</code> to generate</p>
        </div>

        <div style="display:flex;gap:10px;margin-top:24px">
          <button class="btn-primary" id="set-save" style="flex:2">Save settings</button>
          <button class="btn-secondary" id="set-test" style="flex:1">Test connection</button>
        </div>

        <div id="set-status" style="margin-top:12px;font-size:13px;text-align:center;min-height:20px"></div>

        <div style="margin-top:32px;padding-top:20px;border-top:1px solid var(--border)">
          <p style="font-size:11px;color:var(--text-ghost);line-height:1.6">
            All API credentials (Anthropic key, Notion key, database ID) are stored securely in your Cloudflare Worker environment variables — never in this app. Only the Worker URL is needed here.
          </p>
        </div>

        <div style="margin-top:32px;padding-top:20px;border-top:1px solid var(--border)">
          <p class="field-label" style="margin-bottom:8px">Notion Sync</p>
          <p style="font-size:11px;color:var(--text-ghost);line-height:1.6;margin-bottom:12px">
            Import dreams added directly to Notion, remove dreams deleted from Notion, and retry any failed saves.
          </p>
          <button class="btn-secondary" id="set-sync" style="width:100%">Sync from Notion</button>
          <div id="set-sync-status" style="margin-top:10px;font-size:13px;text-align:center;min-height:20px"></div>
        </div>
      </div>
    </div>
  `;

  document.getElementById('set-worker-url').value = settings.workerUrl || '';
  document.getElementById('set-vapid').value = settings.vapidPublicKey || '';

  document.getElementById('set-menu').addEventListener('click', openDrawer);

  document.getElementById('set-save').addEventListener('click', () => {
    db.saveSettings({
      workerUrl:      document.getElementById('set-worker-url').value.trim(),
      vapidPublicKey: document.getElementById('set-vapid').value.trim(),
    });
    showStatus('Settings saved ✓', 'var(--success)');
  });

  document.getElementById('set-test').addEventListener('click', async () => {
    // Save current input values before testing
    db.saveSettings({ workerUrl: document.getElementById('set-worker-url').value.trim() });
    showStatus('Testing...', 'var(--text-faint)');
    const ok = await api.testConnection();
    showStatus(ok ? 'Connected ✓' : 'Connection failed ✗', ok ? 'var(--success)' : 'var(--danger)');
  });

  document.getElementById('set-sync').addEventListener('click', async () => {
    const btn = document.getElementById('set-sync');
    btn.disabled = true;
    showSyncStatus('Syncing…', 'var(--text-faint)');

    try {
      // Collect known notionPageIds — updated after each iteration to avoid re-importing
      let knownIds = db.getDreams().map(d => d.notionPageId).filter(Boolean);
      let totalImported = 0;
      let totalDeleted = 0;

      // Loop until no more dreams to import — handles Cloudflare subrequest limit
      // (free plan: 50 subrequests/invocation; large imports need multiple calls).
      // MAX_ROUNDS guards against a misbehaving worker that ignores knownIds.
      const MAX_ROUNDS = 50;
      for (let round = 0; round < MAX_ROUNDS; round++) {
        const { toImport, toDelete } = await api.sync(knownIds);

        if (toImport.length) db.importDreams(toImport);
        totalImported += toImport.length;

        // Process deletions only on first round — toDelete is stable relative to
        // the initial local state and applying it repeatedly is wasteful.
        if (round === 0) {
          toDelete.forEach(id => db.deleteDream(id));
          totalDeleted = toDelete.length;
        }

        if (toImport.length === 0) break;

        // Add newly imported IDs so next call skips them
        knownIds = db.getDreams().map(d => d.notionPageId).filter(Boolean);
      }

      // Retry local dreams with no notionPageId (failed saves)
      const pending = db.getDreams().filter(d => !d.notionPageId);
      let retryOk = 0;
      for (const dream of pending) {
        try {
          const { notionPageId } = await api.retrySave(dream);
          db.updateDream(dream.id, { notionPageId });
          retryOk++;
        } catch { /* skip, will retry next sync */ }
      }

      // Build summary
      const parts = [];
      if (totalImported) parts.push(`${totalImported} imported`);
      if (totalDeleted)  parts.push(`${totalDeleted} deleted`);
      if (pending.length) parts.push(`${retryOk} of ${pending.length} pending saves retried`);
      const summary = parts.length ? parts.join(', ') : 'Already up to date';
      showSyncStatus(summary + ' ✓', 'var(--success)');

      // Re-render journal if it is the current screen
      if (state.currentScreen === 'journal') navigate('journal');

    } catch (err) {
      showSyncStatus(`Sync failed: ${err.message}`, 'var(--danger)');
    } finally {
      btn.disabled = false;
    }
  });
}

function showStatus(msg, color) {
  const el = document.getElementById('set-status');
  if (el) { el.textContent = msg; el.style.color = color; }
}

function showSyncStatus(msg, color) {
  const el = document.getElementById('set-sync-status');
  if (el) { el.textContent = msg; el.style.color = color; }
}
